# Generated by Django 5.1.7 on 2025-03-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
    ]
