# Generated by Django 5.1.7 on 2025-03-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0002_remove_estadoactivo_activo_activo_estadoactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.CreateModel(
            name='Rol_permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basededatos.permiso')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basededatos.rol')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basededatos.rol_permisos'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='basededatos.Rol_permisos', to='basededatos.permiso'),
        ),
    ]
